// Emoji data ported from Expensify/assets/emojis/common.ts
// Structure matches Expensify's EmojiPicker data format exactly.
// SVG icon imports replaced with emoji character shortcuts for self-contained use.

export type Emoji = {
  code: string;
  name: string;
  types?: readonly string[];
};

export type HeaderEmoji = {
  header: true;
  icon: string; // emoji character used as category icon
  code: string; // category key
  label: string; // display name
};

export type PickerEmoji = Emoji | HeaderEmoji;
export type PickerEmojis = PickerEmoji[];

export const CATEGORIES = [
  { code: 'smileysAndEmotion', icon: '😀', label: 'Smileys' },
  { code: 'peopleAndBody', icon: '👋', label: 'People' },
  { code: 'animalsAndNature', icon: '🐶', label: 'Animals' },
  { code: 'foodAndDrink', icon: '🍔', label: 'Food' },
  { code: 'travelAndPlaces', icon: '✈️', label: 'Travel' },
  { code: 'activities', icon: '⚽', label: 'Activities' },
  { code: 'objects', icon: '💡', label: 'Objects' },
  { code: 'symbols', icon: '☮️', label: 'Symbols' },
  { code: 'flags', icon: '🏳️', label: 'Flags' },
];

export const skinTones = ['🖐', '🖐🏻', '🖐🏼', '🖐🏽', '🖐🏾', '🖐🏿'];

const emojis: PickerEmojis = [
  // ──────────────────────────────────────────
  // SMILEYS & EMOTION
  // ──────────────────────────────────────────
  { header: true, icon: '😀', code: 'smileysAndEmotion', label: 'Smileys & Emotion' },
  { name: 'grinning', code: '😀' },
  { name: 'smiley', code: '😃' },
  { name: 'smile', code: '😄' },
  { name: 'grin', code: '😁' },
  { name: 'laughing', code: '😆' },
  { name: 'sweat_smile', code: '😅' },
  { name: 'rofl', code: '🤣' },
  { name: 'joy', code: '😂' },
  { name: 'slightly_smiling_face', code: '🙂' },
  { name: 'upside_down_face', code: '🙃' },
  { name: 'wink', code: '😉' },
  { name: 'blush', code: '😊' },
  { name: 'innocent', code: '😇' },
  { name: 'heart_eyes', code: '😍' },
  { name: 'smiling_face_with_three_hearts', code: '🥰' },
  { name: 'star_struck', code: '🤩' },
  { name: 'kissing_heart', code: '😘' },
  { name: 'kissing', code: '😗' },
  { name: 'kissing_closed_eyes', code: '😚' },
  { name: 'kissing_smiling_eyes', code: '😙' },
  { name: 'yum', code: '😋' },
  { name: 'stuck_out_tongue', code: '😛' },
  { name: 'stuck_out_tongue_winking_eye', code: '😜' },
  { name: 'zany_face', code: '🤪' },
  { name: 'stuck_out_tongue_closed_eyes', code: '😝' },
  { name: 'money_mouth_face', code: '🤑' },
  { name: 'hugs', code: '🤗' },
  { name: 'thinking', code: '🤔' },
  { name: 'zipper_mouth_face', code: '🤐' },
  { name: 'raised_eyebrow', code: '🤨' },
  { name: 'neutral_face', code: '😐' },
  { name: 'expressionless', code: '😑' },
  { name: 'no_mouth', code: '😶' },
  { name: 'smirk', code: '😏' },
  { name: 'unamused', code: '😒' },
  { name: 'roll_eyes', code: '🙄' },
  { name: 'grimacing', code: '😬' },
  { name: 'lying_face', code: '🤥' },
  { name: 'relieved', code: '😌' },
  { name: 'pensive', code: '😔' },
  { name: 'sleepy', code: '😪' },
  { name: 'drooling_face', code: '🤤' },
  { name: 'sleeping', code: '😴' },
  { name: 'mask', code: '😷' },
  { name: 'face_with_thermometer', code: '🤒' },
  { name: 'face_with_head_bandage', code: '🤕' },
  { name: 'nauseated_face', code: '🤢' },
  { name: 'sneezing_face', code: '🤧' },
  { name: 'hot_face', code: '🥵' },
  { name: 'cold_face', code: '🥶' },
  { name: 'woozy_face', code: '🥴' },
  { name: 'dizzy_face', code: '😵' },
  { name: 'exploding_head', code: '🤯' },
  { name: 'cowboy_hat_face', code: '🤠' },
  { name: 'partying_face', code: '🥳' },
  { name: 'sunglasses', code: '😎' },
  { name: 'nerd_face', code: '🤓' },
  { name: 'monocle_face', code: '🧐' },
  { name: 'confused', code: '😕' },
  { name: 'worried', code: '😟' },
  { name: 'slightly_frowning_face', code: '🙁' },
  { name: 'frowning_face', code: '☹️' },
  { name: 'open_mouth', code: '😮' },
  { name: 'hushed', code: '😯' },
  { name: 'astonished', code: '😲' },
  { name: 'flushed', code: '😳' },
  { name: 'pleading_face', code: '🥺' },
  { name: 'anguished', code: '😧' },
  { name: 'fearful', code: '😨' },
  { name: 'cold_sweat', code: '😰' },
  { name: 'disappointed_relieved', code: '😥' },
  { name: 'cry', code: '😢' },
  { name: 'sob', code: '😭' },
  { name: 'scream', code: '😱' },
  { name: 'confounded', code: '😖' },
  { name: 'persevere', code: '😣' },
  { name: 'disappointed', code: '😞' },
  { name: 'sweat', code: '😓' },
  { name: 'weary', code: '😩' },
  { name: 'tired_face', code: '😫' },
  { name: 'yawning_face', code: '🥱' },
  { name: 'triumph', code: '😤' },
  { name: 'rage', code: '😡' },
  { name: 'angry', code: '😠' },
  { name: 'cursing_face', code: '🤬' },
  { name: 'smiling_imp', code: '😈' },
  { name: 'imp', code: '👿' },
  { name: 'skull', code: '💀' },
  { name: 'skull_and_crossbones', code: '☠️' },
  { name: 'hankey', code: '💩' },
  { name: 'clown_face', code: '🤡' },
  { name: 'ghost', code: '👻' },
  { name: 'alien', code: '👽' },
  { name: 'space_invader', code: '👾' },
  { name: 'robot', code: '🤖' },
  { name: 'smiley_cat', code: '😺' },
  { name: 'joy_cat', code: '😹' },
  { name: 'heart_eyes_cat', code: '😻' },
  { name: 'smirk_cat', code: '😼' },
  { name: 'kissing_cat', code: '😽' },
  { name: 'scream_cat', code: '🙀' },
  { name: 'crying_cat_face', code: '😿' },
  { name: 'pouting_cat', code: '😾' },
  { name: 'see_no_evil', code: '🙈' },
  { name: 'hear_no_evil', code: '🙉' },
  { name: 'speak_no_evil', code: '🙊' },
  { name: 'kiss', code: '💋' },
  { name: 'love_letter', code: '💌' },
  { name: 'cupid', code: '💘' },
  { name: 'sparkling_heart', code: '💖' },
  { name: 'heartpulse', code: '💗' },
  { name: 'heartbeat', code: '💓' },
  { name: 'revolving_hearts', code: '💞' },
  { name: 'two_hearts', code: '💕' },
  { name: 'broken_heart', code: '💔' },
  { name: 'heart', code: '❤️' },
  { name: 'orange_heart', code: '🧡' },
  { name: 'yellow_heart', code: '💛' },
  { name: 'green_heart', code: '💚' },
  { name: 'blue_heart', code: '💙' },
  { name: 'purple_heart', code: '💜' },
  { name: 'black_heart', code: '🖤' },
  { name: 'white_heart', code: '🤍' },
  { name: 'brown_heart', code: '🤎' },
  { name: '100', code: '💯' },
  { name: 'anger', code: '💢' },
  { name: 'boom', code: '💥' },
  { name: 'dizzy', code: '💫' },
  { name: 'sweat_drops', code: '💦' },
  { name: 'dash', code: '💨' },
  { name: 'speech_balloon', code: '💬' },
  { name: 'thought_balloon', code: '💭' },
  { name: 'zzz', code: '💤' },

  // ──────────────────────────────────────────
  // PEOPLE & BODY
  // ──────────────────────────────────────────
  { header: true, icon: '👋', code: 'peopleAndBody', label: 'People & Body' },
  { name: 'wave', code: '👋', types: ['👋🏻', '👋🏼', '👋🏽', '👋🏾', '👋🏿'] },
  { name: 'raised_back_of_hand', code: '🤚', types: ['🤚🏻', '🤚🏼', '🤚🏽', '🤚🏾', '🤚🏿'] },
  { name: 'hand', code: '✋', types: ['✋🏻', '✋🏼', '✋🏽', '✋🏾', '✋🏿'] },
  { name: 'vulcan_salute', code: '🖖', types: ['🖖🏻', '🖖🏼', '🖖🏽', '🖖🏾', '🖖🏿'] },
  { name: 'ok_hand', code: '👌', types: ['👌🏻', '👌🏼', '👌🏽', '👌🏾', '👌🏿'] },
  { name: 'pinching_hand', code: '🤏', types: ['🤏🏻', '🤏🏼', '🤏🏽', '🤏🏾', '🤏🏿'] },
  { name: 'v', code: '✌️', types: ['✌🏻', '✌🏼', '✌🏽', '✌🏾', '✌🏿'] },
  { name: 'crossed_fingers', code: '🤞', types: ['🤞🏻', '🤞🏼', '🤞🏽', '🤞🏾', '🤞🏿'] },
  { name: 'love_you_gesture', code: '🤟', types: ['🤟🏻', '🤟🏼', '🤟🏽', '🤟🏾', '🤟🏿'] },
  { name: 'metal', code: '🤘', types: ['🤘🏻', '🤘🏼', '🤘🏽', '🤘🏾', '🤘🏿'] },
  { name: 'call_me_hand', code: '🤙', types: ['🤙🏻', '🤙🏼', '🤙🏽', '🤙🏾', '🤙🏿'] },
  { name: 'point_left', code: '👈', types: ['👈🏻', '👈🏼', '👈🏽', '👈🏾', '👈🏿'] },
  { name: 'point_right', code: '👉', types: ['👉🏻', '👉🏼', '👉🏽', '👉🏾', '👉🏿'] },
  { name: 'point_up_2', code: '👆', types: ['👆🏻', '👆🏼', '👆🏽', '👆🏾', '👆🏿'] },
  { name: 'fu', code: '🖕', types: ['🖕🏻', '🖕🏼', '🖕🏽', '🖕🏾', '🖕🏿'] },
  { name: 'point_down', code: '👇', types: ['👇🏻', '👇🏼', '👇🏽', '👇🏾', '👇🏿'] },
  { name: 'point_up', code: '☝️', types: ['☝🏻', '☝🏼', '☝🏽', '☝🏾', '☝🏿'] },
  { name: 'thumbsup', code: '👍', types: ['👍🏻', '👍🏼', '👍🏽', '👍🏾', '👍🏿'] },
  { name: 'thumbsdown', code: '👎', types: ['👎🏻', '👎🏼', '👎🏽', '👎🏾', '👎🏿'] },
  { name: 'fist', code: '✊', types: ['✊🏻', '✊🏼', '✊🏽', '✊🏾', '✊🏿'] },
  { name: 'facepunch', code: '👊', types: ['👊🏻', '👊🏼', '👊🏽', '👊🏾', '👊🏿'] },
  { name: 'left_facing_fist', code: '🤛', types: ['🤛🏻', '🤛🏼', '🤛🏽', '🤛🏾', '🤛🏿'] },
  { name: 'right_facing_fist', code: '🤜', types: ['🤜🏻', '🤜🏼', '🤜🏽', '🤜🏾', '🤜🏿'] },
  { name: 'clap', code: '👏', types: ['👏🏻', '👏🏼', '👏🏽', '👏🏾', '👏🏿'] },
  { name: 'raised_hands', code: '🙌', types: ['🙌🏻', '🙌🏼', '🙌🏽', '🙌🏾', '🙌🏿'] },
  { name: 'pray', code: '🙏', types: ['🙏🏻', '🙏🏼', '🙏🏽', '🙏🏾', '🙏🏿'] },
  { name: 'handshake', code: '🤝' },
  { name: 'muscle', code: '💪', types: ['💪🏻', '💪🏼', '💪🏽', '💪🏾', '💪🏿'] },
  { name: 'ear', code: '👂', types: ['👂🏻', '👂🏼', '👂🏽', '👂🏾', '👂🏿'] },
  { name: 'nose', code: '👃', types: ['👃🏻', '👃🏼', '👃🏽', '👃🏾', '👃🏿'] },
  { name: 'eyes', code: '👀' },
  { name: 'eye', code: '👁️' },
  { name: 'tongue', code: '👅' },
  { name: 'lips', code: '👄' },
  { name: 'brain', code: '🧠' },
  { name: 'baby', code: '👶', types: ['👶🏻', '👶🏼', '👶🏽', '👶🏾', '👶🏿'] },
  { name: 'child', code: '🧒', types: ['🧒🏻', '🧒🏼', '🧒🏽', '🧒🏾', '🧒🏿'] },
  { name: 'boy', code: '👦', types: ['👦🏻', '👦🏼', '👦🏽', '👦🏾', '👦🏿'] },
  { name: 'girl', code: '👧', types: ['👧🏻', '👧🏼', '👧🏽', '👧🏾', '👧🏿'] },
  { name: 'adult', code: '🧑', types: ['🧑🏻', '🧑🏼', '🧑🏽', '🧑🏾', '🧑🏿'] },
  { name: 'man', code: '👨', types: ['👨🏻', '👨🏼', '👨🏽', '👨🏾', '👨🏿'] },
  { name: 'woman', code: '👩', types: ['👩🏻', '👩🏼', '👩🏽', '👩🏾', '👩🏿'] },
  { name: 'older_adult', code: '🧓', types: ['🧓🏻', '🧓🏼', '🧓🏽', '🧓🏾', '🧓🏿'] },
  { name: 'older_man', code: '👴', types: ['👴🏻', '👴🏼', '👴🏽', '👴🏾', '👴🏿'] },
  { name: 'older_woman', code: '👵', types: ['👵🏻', '👵🏼', '👵🏽', '👵🏾', '👵🏿'] },
  { name: 'person_frowning', code: '🙍', types: ['🙍🏻', '🙍🏼', '🙍🏽', '🙍🏾', '🙍🏿'] },
  { name: 'person_with_pouting_face', code: '🙎', types: ['🙎🏻', '🙎🏼', '🙎🏽', '🙎🏾', '🙎🏿'] },
  { name: 'no_good', code: '🙅', types: ['🙅🏻', '🙅🏼', '🙅🏽', '🙅🏾', '🙅🏿'] },
  { name: 'ok_woman', code: '🙆', types: ['🙆🏻', '🙆🏼', '🙆🏽', '🙆🏾', '🙆🏿'] },
  { name: 'information_desk_person', code: '💁', types: ['💁🏻', '💁🏼', '💁🏽', '💁🏾', '💁🏿'] },
  { name: 'raising_hand', code: '🙋', types: ['🙋🏻', '🙋🏼', '🙋🏽', '🙋🏾', '🙋🏿'] },
  { name: 'deaf_person', code: '🧏', types: ['🧏🏻', '🧏🏼', '🧏🏽', '🧏🏾', '🧏🏿'] },
  { name: 'bow', code: '🙇', types: ['🙇🏻', '🙇🏼', '🙇🏽', '🙇🏾', '🙇🏿'] },
  { name: 'facepalm', code: '🤦', types: ['🤦🏻', '🤦🏼', '🤦🏽', '🤦🏾', '🤦🏿'] },
  { name: 'shrug', code: '🤷', types: ['🤷🏻', '🤷🏼', '🤷🏽', '🤷🏾', '🤷🏿'] },
  { name: 'health_worker', code: '🧑‍⚕️', types: ['👨‍⚕️', '👩‍⚕️'] },
  { name: 'student', code: '🧑‍🎓', types: ['👨‍🎓', '👩‍🎓'] },
  { name: 'teacher', code: '🧑‍🏫', types: ['👨‍🏫', '👩‍🏫'] },
  { name: 'judge', code: '🧑‍⚖️', types: ['👨‍⚖️', '👩‍⚖️'] },
  { name: 'farmer', code: '🧑‍🌾', types: ['👨‍🌾', '👩‍🌾'] },
  { name: 'cook', code: '🧑‍🍳', types: ['👨‍🍳', '👩‍🍳'] },
  { name: 'mechanic', code: '🧑‍🔧', types: ['👨‍🔧', '👩‍🔧'] },
  { name: 'factory_worker', code: '🧑‍🏭', types: ['👨‍🏭', '👩‍🏭'] },
  { name: 'office_worker', code: '🧑‍💼', types: ['👨‍💼', '👩‍💼'] },
  { name: 'scientist', code: '🧑‍🔬', types: ['👨‍🔬', '👩‍🔬'] },
  { name: 'technologist', code: '🧑‍💻', types: ['👨‍💻', '👩‍💻'] },
  { name: 'singer', code: '🧑‍🎤', types: ['👨‍🎤', '👩‍🎤'] },
  { name: 'artist', code: '🧑‍🎨', types: ['👨‍🎨', '👩‍🎨'] },
  { name: 'pilot', code: '🧑‍✈️', types: ['👨‍✈️', '👩‍✈️'] },
  { name: 'astronaut', code: '🧑‍🚀', types: ['👨‍🚀', '👩‍🚀'] },
  { name: 'firefighter', code: '🧑‍🚒', types: ['👨‍🚒', '👩‍🚒'] },
  { name: 'police_officer', code: '👮', types: ['👮🏻', '👮🏼', '👮🏽', '👮🏾', '👮🏿'] },
  { name: 'detective', code: '🕵️', types: ['🕵🏻', '🕵🏼', '🕵🏽', '🕵🏾', '🕵🏿'] },
  { name: 'guard', code: '💂', types: ['💂🏻', '💂🏼', '💂🏽', '💂🏾', '💂🏿'] },
  { name: 'ninja', code: '🥷', types: ['🥷🏻', '🥷🏼', '🥷🏽', '🥷🏾', '🥷🏿'] },
  { name: 'construction_worker', code: '👷', types: ['👷🏻', '👷🏼', '👷🏽', '👷🏾', '👷🏿'] },
  { name: 'prince', code: '🤴', types: ['🤴🏻', '🤴🏼', '🤴🏽', '🤴🏾', '🤴🏿'] },
  { name: 'princess', code: '👸', types: ['👸🏻', '👸🏼', '👸🏽', '👸🏾', '👸🏿'] },
  { name: 'person_with_turban', code: '👳', types: ['👳🏻', '👳🏼', '👳🏽', '👳🏾', '👳🏿'] },
  { name: 'man_with_gua_pi_mao', code: '👲', types: ['👲🏻', '👲🏼', '👲🏽', '👲🏾', '👲🏿'] },
  { name: 'woman_with_headscarf', code: '🧕', types: ['🧕🏻', '🧕🏼', '🧕🏽', '🧕🏾', '🧕🏿'] },
  { name: 'bride_with_veil', code: '👰', types: ['👰🏻', '👰🏼', '👰🏽', '👰🏾', '👰🏿'] },
  { name: 'man_in_tuxedo', code: '🤵', types: ['🤵🏻', '🤵🏼', '🤵🏽', '🤵🏾', '🤵🏿'] },
  { name: 'pregnant_woman', code: '🤰', types: ['🤰🏻', '🤰🏼', '🤰🏽', '🤰🏾', '🤰🏿'] },
  { name: 'breast_feeding', code: '🤱', types: ['🤱🏻', '🤱🏼', '🤱🏽', '🤱🏾', '🤱🏿'] },
  { name: 'angel', code: '👼', types: ['👼🏻', '👼🏼', '👼🏽', '👼🏾', '👼🏿'] },
  { name: 'santa', code: '🎅', types: ['🎅🏻', '🎅🏼', '🎅🏽', '🎅🏾', '🎅🏿'] },
  { name: 'mrs_claus', code: '🤶', types: ['🤶🏻', '🤶🏼', '🤶🏽', '🤶🏾', '🤶🏿'] },
  { name: 'mage', code: '🧙', types: ['🧙🏻', '🧙🏼', '🧙🏽', '🧙🏾', '🧙🏿'] },
  { name: 'elf', code: '🧝', types: ['🧝🏻', '🧝🏼', '🧝🏽', '🧝🏾', '🧝🏿'] },
  { name: 'vampire', code: '🧛', types: ['🧛🏻', '🧛🏼', '🧛🏽', '🧛🏾', '🧛🏿'] },
  { name: 'zombie', code: '🧟' },
  { name: 'genie', code: '🧞' },
  { name: 'mermaid', code: '🧜', types: ['🧜🏻', '🧜🏼', '🧜🏽', '🧜🏾', '🧜🏿'] },
  { name: 'fairy', code: '🧚', types: ['🧚🏻', '🧚🏼', '🧚🏽', '🧚🏾', '🧚🏿'] },
  { name: 'superhero', code: '🦸', types: ['🦸🏻', '🦸🏼', '🦸🏽', '🦸🏾', '🦸🏿'] },
  { name: 'supervillain', code: '🦹', types: ['🦹🏻', '🦹🏼', '🦹🏽', '🦹🏾', '🦹🏿'] },
  { name: 'runner', code: '🏃', types: ['🏃🏻', '🏃🏼', '🏃🏽', '🏃🏾', '🏃🏿'] },
  { name: 'walking', code: '🚶', types: ['🚶🏻', '🚶🏼', '🚶🏽', '🚶🏾', '🚶🏿'] },
  { name: 'standing_person', code: '🧍', types: ['🧍🏻', '🧍🏼', '🧍🏽', '🧍🏾', '🧍🏿'] },
  { name: 'kneeling_person', code: '🧎', types: ['🧎🏻', '🧎🏼', '🧎🏽', '🧎🏾', '🧎🏿'] },
  { name: 'person_with_probing_cane', code: '🧑‍🦯', types: ['👨‍🦯', '👩‍🦯'] },
  { name: 'person_in_motorized_wheelchair', code: '🧑‍🦼', types: ['👨‍🦼', '👩‍🦼'] },
  { name: 'person_in_manual_wheelchair', code: '🧑‍🦽', types: ['👨‍🦽', '👩‍🦽'] },
  { name: 'dancer', code: '💃', types: ['💃🏻', '💃🏼', '💃🏽', '💃🏾', '💃🏿'] },
  { name: 'man_dancing', code: '🕺', types: ['🕺🏻', '🕺🏼', '🕺🏽', '🕺🏾', '🕺🏿'] },
  { name: 'people_with_bunny_ears_partying', code: '👯' },
  { name: 'men_wrestling', code: '🤼' },
  { name: 'couple', code: '👫', types: ['👫🏻', '👫🏼', '👫🏽', '👫🏾', '👫🏿'] },
  { name: 'two_men_holding_hands', code: '👬', types: ['👬🏻', '👬🏼', '👬🏽', '👬🏾', '👬🏿'] },
  { name: 'two_women_holding_hands', code: '👭', types: ['👭🏻', '👭🏼', '👭🏽', '👭🏾', '👭🏿'] },
  { name: 'couplekiss', code: '💏', types: ['💏🏻', '💏🏼', '💏🏽', '💏🏾', '💏🏿'] },
  { name: 'couple_with_heart', code: '💑', types: ['💑🏻', '💑🏼', '💑🏽', '💑🏾', '💑🏿'] },
  { name: 'family', code: '👪' },
  { name: 'footprints', code: '👣' },

  // ──────────────────────────────────────────
  // ANIMALS & NATURE
  // ──────────────────────────────────────────
  { header: true, icon: '🐶', code: 'animalsAndNature', label: 'Animals & Nature' },
  { name: 'dog', code: '🐶' },
  { name: 'cat', code: '🐱' },
  { name: 'mouse', code: '🐭' },
  { name: 'hamster', code: '🐹' },
  { name: 'rabbit', code: '🐰' },
  { name: 'fox_face', code: '🦊' },
  { name: 'bear', code: '🐻' },
  { name: 'panda_face', code: '🐼' },
  { name: 'polar_bear', code: '🐻‍❄️' },
  { name: 'koala', code: '🐨' },
  { name: 'tiger', code: '🐯' },
  { name: 'lion', code: '🦁' },
  { name: 'cow', code: '🐮' },
  { name: 'pig', code: '🐷' },
  { name: 'pig_nose', code: '🐽' },
  { name: 'frog', code: '🐸' },
  { name: 'monkey_face', code: '🐵' },
  { name: 'see_no_evil_monkey', code: '🙈' },
  { name: 'chicken', code: '🐔' },
  { name: 'penguin', code: '🐧' },
  { name: 'bird', code: '🐦' },
  { name: 'hatching_chick', code: '🐣' },
  { name: 'baby_chick', code: '🐤' },
  { name: 'front-facing_baby_chick', code: '🐥' },
  { name: 'duck', code: '🦆' },
  { name: 'eagle', code: '🦅' },
  { name: 'owl', code: '🦉' },
  { name: 'bat', code: '🦇' },
  { name: 'wolf', code: '🐺' },
  { name: 'boar', code: '🐗' },
  { name: 'horse', code: '🐴' },
  { name: 'unicorn', code: '🦄' },
  { name: 'bee', code: '🐝' },
  { name: 'bug', code: '🐛' },
  { name: 'butterfly', code: '🦋' },
  { name: 'snail', code: '🐌' },
  { name: 'shell', code: '🐚' },
  { name: 'beetle', code: '🐞' },
  { name: 'ant', code: '🐜' },
  { name: 'mosquito', code: '🦟' },
  { name: 'cricket', code: '🦗' },
  { name: 'cockroach', code: '🪳' },
  { name: 'spider', code: '🕷️' },
  { name: 'spider_web', code: '🕸️' },
  { name: 'scorpion', code: '🦂' },
  { name: 'turtle', code: '🐢' },
  { name: 'snake', code: '🐍' },
  { name: 'lizard', code: '🦎' },
  { name: 'dragon_face', code: '🐲' },
  { name: 'dragon', code: '🐉' },
  { name: 'sauropod', code: '🦕' },
  { name: 't-rex', code: '🦖' },
  { name: 'whale', code: '🐳' },
  { name: 'whale2', code: '🐋' },
  { name: 'dolphin', code: '🐬' },
  { name: 'seal', code: '🦭' },
  { name: 'fish', code: '🐟' },
  { name: 'tropical_fish', code: '🐠' },
  { name: 'blowfish', code: '🐡' },
  { name: 'shark', code: '🦈' },
  { name: 'octopus', code: '🐙' },
  { name: 'crab', code: '🦀' },
  { name: 'lobster', code: '🦞' },
  { name: 'shrimp', code: '🦐' },
  { name: 'squid', code: '🦑' },
  { name: 'oyster', code: '🦪' },
  { name: 'sneezing_face', code: '🤧' },
  { name: 'bouquet', code: '💐' },
  { name: 'cherry_blossom', code: '🌸' },
  { name: 'white_flower', code: '💮' },
  { name: 'rosette', code: '🏵️' },
  { name: 'rose', code: '🌹' },
  { name: 'wilted_flower', code: '🥀' },
  { name: 'hibiscus', code: '🌺' },
  { name: 'sunflower', code: '🌻' },
  { name: 'blossom', code: '🌼' },
  { name: 'tulip', code: '🌷' },
  { name: 'seedling', code: '🌱' },
  { name: 'evergreen_tree', code: '🌲' },
  { name: 'deciduous_tree', code: '🌳' },
  { name: 'palm_tree', code: '🌴' },
  { name: 'cactus', code: '🌵' },
  { name: 'ear_of_rice', code: '🌾' },
  { name: 'herb', code: '🌿' },
  { name: 'shamrock', code: '☘️' },
  { name: 'four_leaf_clover', code: '🍀' },
  { name: 'maple_leaf', code: '🍁' },
  { name: 'fallen_leaf', code: '🍂' },
  { name: 'leaves', code: '🍃' },
  { name: 'mushroom', code: '🍄' },
  { name: 'chestnut', code: '🌰' },
  { name: 'earth_africa', code: '🌍' },
  { name: 'earth_americas', code: '🌎' },
  { name: 'earth_asia', code: '🌏' },
  { name: 'new_moon', code: '🌑' },
  { name: 'crescent_moon', code: '🌙' },
  { name: 'sun', code: '☀️' },
  { name: 'full_moon', code: '🌕' },
  { name: 'star', code: '⭐' },
  { name: 'star2', code: '🌟' },
  { name: 'sparkles', code: '✨' },
  { name: 'zap', code: '⚡' },
  { name: 'rainbow', code: '🌈' },
  { name: 'cloud', code: '☁️' },
  { name: 'snowflake', code: '❄️' },
  { name: 'snowman', code: '⛄' },
  { name: 'fire', code: '🔥' },
  { name: 'droplet', code: '💧' },
  { name: 'ocean', code: '🌊' },

  // ──────────────────────────────────────────
  // FOOD & DRINK
  // ──────────────────────────────────────────
  { header: true, icon: '🍔', code: 'foodAndDrink', label: 'Food & Drink' },
  { name: 'grapes', code: '🍇' },
  { name: 'melon', code: '🍈' },
  { name: 'watermelon', code: '🍉' },
  { name: 'tangerine', code: '🍊' },
  { name: 'lemon', code: '🍋' },
  { name: 'banana', code: '🍌' },
  { name: 'pineapple', code: '🍍' },
  { name: 'mango', code: '🥭' },
  { name: 'apple', code: '🍎' },
  { name: 'green_apple', code: '🍏' },
  { name: 'pear', code: '🍐' },
  { name: 'peach', code: '🍑' },
  { name: 'cherries', code: '🍒' },
  { name: 'strawberry', code: '🍓' },
  { name: 'blueberries', code: '🫐' },
  { name: 'kiwi_fruit', code: '🥝' },
  { name: 'tomato', code: '🍅' },
  { name: 'coconut', code: '🥥' },
  { name: 'avocado', code: '🥑' },
  { name: 'eggplant', code: '🍆' },
  { name: 'potato', code: '🥔' },
  { name: 'carrot', code: '🥕' },
  { name: 'corn', code: '🌽' },
  { name: 'hot_pepper', code: '🌶️' },
  { name: 'cucumber', code: '🥒' },
  { name: 'leafy_green', code: '🥬' },
  { name: 'broccoli', code: '🥦' },
  { name: 'garlic', code: '🧄' },
  { name: 'onion', code: '🧅' },
  { name: 'mushroom', code: '🍄' },
  { name: 'peanuts', code: '🥜' },
  { name: 'chestnut', code: '🌰' },
  { name: 'bread', code: '🍞' },
  { name: 'croissant', code: '🥐' },
  { name: 'baguette_bread', code: '🥖' },
  { name: 'flatbread', code: '🫓' },
  { name: 'pretzel', code: '🥨' },
  { name: 'bagel', code: '🥯' },
  { name: 'pancakes', code: '🥞' },
  { name: 'waffle', code: '🧇' },
  { name: 'cheese_wedge', code: '🧀' },
  { name: 'meat_on_bone', code: '🍖' },
  { name: 'poultry_leg', code: '🍗' },
  { name: 'cut_of_meat', code: '🥩' },
  { name: 'bacon', code: '🥓' },
  { name: 'hamburger', code: '🍔' },
  { name: 'fries', code: '🍟' },
  { name: 'pizza', code: '🍕' },
  { name: 'hotdog', code: '🌭' },
  { name: 'sandwich', code: '🥪' },
  { name: 'taco', code: '🌮' },
  { name: 'burrito', code: '🌯' },
  { name: 'tamale', code: '🫔' },
  { name: 'stuffed_flatbread', code: '🥙' },
  { name: 'falafel', code: '🧆' },
  { name: 'egg', code: '🥚' },
  { name: 'cooking', code: '🍳' },
  { name: 'shallow_pan_of_food', code: '🥘' },
  { name: 'stew', code: '🍲' },
  { name: 'bowl_with_spoon', code: '🥣' },
  { name: 'green_salad', code: '🥗' },
  { name: 'popcorn', code: '🍿' },
  { name: 'butter', code: '🧈' },
  { name: 'salt', code: '🧂' },
  { name: 'canned_food', code: '🥫' },
  { name: 'bento', code: '🍱' },
  { name: 'rice_cracker', code: '🍘' },
  { name: 'rice_ball', code: '🍙' },
  { name: 'rice', code: '🍚' },
  { name: 'curry', code: '🍛' },
  { name: 'ramen', code: '🍜' },
  { name: 'spaghetti', code: '🍝' },
  { name: 'sweet_potato', code: '🍠' },
  { name: 'oden', code: '🍢' },
  { name: 'sushi', code: '🍣' },
  { name: 'fried_shrimp', code: '🍤' },
  { name: 'fish_cake', code: '🍥' },
  { name: 'moon_cake', code: '🥮' },
  { name: 'dango', code: '🍡' },
  { name: 'dumpling', code: '🥟' },
  { name: 'fortune_cookie', code: '🥠' },
  { name: 'takeout_box', code: '🥡' },
  { name: 'crab', code: '🦀' },
  { name: 'lobster', code: '🦞' },
  { name: 'shrimp', code: '🦐' },
  { name: 'squid', code: '🦑' },
  { name: 'oyster', code: '🦪' },
  { name: 'icecream', code: '🍦' },
  { name: 'shaved_ice', code: '🍧' },
  { name: 'ice_cream', code: '🍨' },
  { name: 'doughnut', code: '🍩' },
  { name: 'cookie', code: '🍪' },
  { name: 'birthday', code: '🎂' },
  { name: 'cake', code: '🍰' },
  { name: 'cupcake', code: '🧁' },
  { name: 'pie', code: '🥧' },
  { name: 'chocolate_bar', code: '🍫' },
  { name: 'candy', code: '🍬' },
  { name: 'lollipop', code: '🍭' },
  { name: 'custard', code: '🍮' },
  { name: 'honey_pot', code: '🍯' },
  { name: 'coffee', code: '☕' },
  { name: 'tea', code: '🍵' },
  { name: 'bubble_tea', code: '🧋' },
  { name: 'sake', code: '🍶' },
  { name: 'champagne', code: '🍾' },
  { name: 'wine_glass', code: '🍷' },
  { name: 'cocktail', code: '🍸' },
  { name: 'tropical_drink', code: '🍹' },
  { name: 'beer', code: '🍺' },
  { name: 'beers', code: '🍻' },
  { name: 'clinking_glasses', code: '🥂' },
  { name: 'tumbler_glass', code: '🥃' },
  { name: 'cup_with_straw', code: '🥤' },
  { name: 'beverage_box', code: '🧃' },
  { name: 'mate', code: '🧉' },
  { name: 'ice', code: '🧊' },
  { name: 'chopsticks', code: '🥢' },
  { name: 'plate_with_cutlery', code: '🍽️' },
  { name: 'fork_and_knife', code: '🍴' },
  { name: 'spoon', code: '🥄' },
  { name: 'knife', code: '🔪' },
  { name: 'amphora', code: '🏺' },

  // ──────────────────────────────────────────
  // TRAVEL & PLACES
  // ──────────────────────────────────────────
  { header: true, icon: '✈️', code: 'travelAndPlaces', label: 'Travel & Places' },
  { name: 'earth_globe_europe-africa', code: '🌍' },
  { name: 'earth_globe_americas', code: '🌎' },
  { name: 'earth_globe_asia-australia', code: '🌏' },
  { name: 'globe_with_meridians', code: '🌐' },
  { name: 'japan', code: '🗾' },
  { name: 'compass', code: '🧭' },
  { name: 'snow_capped_mountain', code: '🏔️' },
  { name: 'mountain', code: '⛰️' },
  { name: 'volcano', code: '🌋' },
  { name: 'mount_fuji', code: '🗻' },
  { name: 'camping', code: '🏕️' },
  { name: 'beach_with_umbrella', code: '🏖️' },
  { name: 'desert', code: '🏜️' },
  { name: 'desert_island', code: '🏝️' },
  { name: 'national_park', code: '🏞️' },
  { name: 'stadium', code: '🏟️' },
  { name: 'classical_building', code: '🏛️' },
  { name: 'building_construction', code: '🏗️' },
  { name: 'bricks', code: '🧱' },
  { name: 'rock', code: '🪨' },
  { name: 'wood', code: '🪵' },
  { name: 'hut', code: '🛖' },
  { name: 'house', code: '🏠' },
  { name: 'house_with_garden', code: '🏡' },
  { name: 'office', code: '🏢' },
  { name: 'japanese_post_office', code: '🏣' },
  { name: 'european_post_office', code: '🏤' },
  { name: 'hospital', code: '🏥' },
  { name: 'bank', code: '🏦' },
  { name: 'hotel', code: '🏨' },
  { name: 'convenience_store', code: '🏪' },
  { name: 'school', code: '🏫' },
  { name: 'love_hotel', code: '🏩' },
  { name: 'wedding', code: '💒' },
  { name: 'european_castle', code: '🏰' },
  { name: 'japanese_castle', code: '🏯' },
  { name: 'city_sunrise', code: '🌇' },
  { name: 'city_sunset', code: '🌆' },
  { name: 'cityscape', code: '🏙️' },
  { name: 'night_with_stars', code: '🌃' },
  { name: 'bridge_at_night', code: '🌉' },
  { name: 'milky_way', code: '🌌' },
  { name: 'stars', code: '🌠' },
  { name: 'sparkler', code: '🎇' },
  { name: 'fireworks', code: '🎆' },
  { name: 'fog', code: '🌁' },
  { name: 'sunrise_over_mountains', code: '🌄' },
  { name: 'sunrise', code: '🌅' },
  { name: 'foggy', code: '🌁' },
  { name: 'moai', code: '🗿' },
  { name: 'statue_of_liberty', code: '🗽' },
  { name: 'railway_track', code: '🛤️' },
  { name: 'motorway', code: '🛣️' },
  { name: 'railway_car', code: '🚃' },
  { name: 'bullettrain_side', code: '🚄' },
  { name: 'bullettrain_front', code: '🚅' },
  { name: 'train2', code: '🚆' },
  { name: 'metro', code: '🚇' },
  { name: 'light_rail', code: '🚈' },
  { name: 'station', code: '🚉' },
  { name: 'tram', code: '🚊' },
  { name: 'monorail', code: '🚝' },
  { name: 'mountain_railway', code: '🚞' },
  { name: 'train', code: '🚋' },
  { name: 'bus', code: '🚌' },
  { name: 'oncoming_bus', code: '🚍' },
  { name: 'trolleybus', code: '🚎' },
  { name: 'minibus', code: '🚐' },
  { name: 'ambulance', code: '🚑' },
  { name: 'fire_engine', code: '🚒' },
  { name: 'police_car', code: '🚓' },
  { name: 'oncoming_police_car', code: '🚔' },
  { name: 'taxi', code: '🚕' },
  { name: 'oncoming_taxi', code: '🚖' },
  { name: 'car', code: '🚗' },
  { name: 'oncoming_automobile', code: '🚘' },
  { name: 'blue_car', code: '🚙' },
  { name: 'pickup_truck', code: '🛻' },
  { name: 'truck', code: '🚚' },
  { name: 'articulated_lorry', code: '🚛' },
  { name: 'tractor', code: '🚜' },
  { name: 'racing_car', code: '🏎️' },
  { name: 'motor_scooter', code: '🛵' },
  { name: 'motorbike', code: '🏍️' },
  { name: 'kick_scooter', code: '🛴' },
  { name: 'skateboard', code: '🛹' },
  { name: 'roller_skate', code: '🛼' },
  { name: 'bike', code: '🚲' },
  { name: 'flying_saucer', code: '🛸' },
  { name: 'helicopter', code: '🚁' },
  { name: 'small_airplane', code: '🛩️' },
  { name: 'airplane', code: '✈️' },
  { name: 'seat', code: '💺' },
  { name: 'rocket', code: '🚀' },
  { name: 'parachute', code: '🪂' },
  { name: 'luggage', code: '🧳' },
  { name: 'anchor', code: '⚓' },
  { name: 'boat', code: '⛵' },
  { name: 'canoe', code: '🛶' },
  { name: 'ship', code: '🚢' },
  { name: 'ferry', code: '⛴️' },
  { name: 'motor_boat', code: '🛥️' },
  { name: 'speedboat', code: '🚤' },
  { name: 'fuelpump', code: '⛽' },
  { name: 'busstop', code: '🚏' },
  { name: 'traffic_light', code: '🚥' },
  { name: 'vertical_traffic_light', code: '🚦' },
  { name: 'stop_sign', code: '🛑' },
  { name: 'construction', code: '🚧' },

  // ──────────────────────────────────────────
  // ACTIVITIES
  // ──────────────────────────────────────────
  { header: true, icon: '⚽', code: 'activities', label: 'Activities' },
  { name: 'soccer', code: '⚽' },
  { name: 'basketball', code: '🏀' },
  { name: 'football', code: '🏈' },
  { name: 'baseball', code: '⚾' },
  { name: 'softball', code: '🥎' },
  { name: 'tennis', code: '🎾' },
  { name: 'volleyball', code: '🏐' },
  { name: 'rugby_football', code: '🏉' },
  { name: 'flying_disc', code: '🥏' },
  { name: '8ball', code: '🎱' },
  { name: 'ping_pong', code: '🏓' },
  { name: 'badminton', code: '🏸' },
  { name: 'hockey', code: '🏒' },
  { name: 'field_hockey', code: '🏑' },
  { name: 'lacrosse', code: '🥍' },
  { name: 'cricket_game', code: '🏏' },
  { name: 'ski', code: '⛷️' },
  { name: 'snowboarder', code: '🏂' },
  { name: 'person_golfing', code: '🏌️' },
  { name: 'person_surfing', code: '🏄' },
  { name: 'person_rowing_boat', code: '🚣' },
  { name: 'person_swimming', code: '🏊' },
  { name: 'person_bouncing_ball', code: '⛹️' },
  { name: 'person_lifting_weights', code: '🏋️' },
  { name: 'person_biking', code: '🚴' },
  { name: 'person_mountain_biking', code: '🚵' },
  { name: 'horse_racing', code: '🏇' },
  { name: 'medal_sports', code: '🏅' },
  { name: '1st_place_medal', code: '🥇' },
  { name: '2nd_place_medal', code: '🥈' },
  { name: '3rd_place_medal', code: '🥉' },
  { name: 'trophy', code: '🏆' },
  { name: 'ticket', code: '🎫' },
  { name: 'tickets', code: '🎟️' },
  { name: 'circus_tent', code: '🎪' },
  { name: 'performing_arts', code: '🎭' },
  { name: 'art', code: '🎨' },
  { name: 'slot_machine', code: '🎰' },
  { name: 'game_die', code: '🎲' },
  { name: 'jigsaw', code: '🧩' },
  { name: 'teddy_bear', code: '🧸' },
  { name: 'spades', code: '♠️' },
  { name: 'hearts', code: '♥️' },
  { name: 'diamonds', code: '♦️' },
  { name: 'clubs', code: '♣️' },
  { name: 'chess_pawn', code: '♟️' },
  { name: 'joker', code: '🃏' },
  { name: 'mahjong', code: '🀄' },
  { name: 'flower_playing_cards', code: '🎴' },
  { name: 'video_game', code: '🎮' },
  { name: 'joystick', code: '🕹️' },

  // ──────────────────────────────────────────
  // OBJECTS
  // ──────────────────────────────────────────
  { header: true, icon: '💡', code: 'objects', label: 'Objects' },
  { name: 'mute', code: '🔇' },
  { name: 'sound', code: '🔉' },
  { name: 'loud_sound', code: '🔊' },
  { name: 'loudspeaker', code: '📢' },
  { name: 'mega', code: '📣' },
  { name: 'postal_horn', code: '📯' },
  { name: 'bell', code: '🔔' },
  { name: 'no_bell', code: '🔕' },
  { name: 'musical_score', code: '🎼' },
  { name: 'musical_note', code: '🎵' },
  { name: 'notes', code: '🎶' },
  { name: 'studio_microphone', code: '🎙️' },
  { name: 'level_slider', code: '🎚️' },
  { name: 'control_knobs', code: '🎛️' },
  { name: 'microphone', code: '🎤' },
  { name: 'headphones', code: '🎧' },
  { name: 'radio', code: '📻' },
  { name: 'saxophone', code: '🎷' },
  { name: 'accordion', code: '🪗' },
  { name: 'guitar', code: '🎸' },
  { name: 'musical_keyboard', code: '🎹' },
  { name: 'trumpet', code: '🎺' },
  { name: 'violin', code: '🎻' },
  { name: 'banjo', code: '🪕' },
  { name: 'drum', code: '🥁' },
  { name: 'long_drum', code: '🪘' },
  { name: 'iphone', code: '📱' },
  { name: 'calling', code: '📲' },
  { name: 'phone', code: '☎️' },
  { name: 'telephone_receiver', code: '📞' },
  { name: 'pager', code: '📟' },
  { name: 'fax', code: '📠' },
  { name: 'battery', code: '🔋' },
  { name: 'electric_plug', code: '🔌' },
  { name: 'computer', code: '💻' },
  { name: 'desktop_computer', code: '🖥️' },
  { name: 'printer', code: '🖨️' },
  { name: 'keyboard', code: '⌨️' },
  { name: 'computer_mouse', code: '🖱️' },
  { name: 'trackball', code: '🖲️' },
  { name: 'minidisc', code: '💽' },
  { name: 'floppy_disk', code: '💾' },
  { name: 'cd', code: '💿' },
  { name: 'dvd', code: '📀' },
  { name: 'abacus', code: '🧮' },
  { name: 'movie_camera', code: '🎥' },
  { name: 'film_strip', code: '🎞️' },
  { name: 'film_projector', code: '📽️' },
  { name: 'clapper', code: '🎬' },
  { name: 'tv', code: '📺' },
  { name: 'camera', code: '📷' },
  { name: 'camera_flash', code: '📸' },
  { name: 'video_camera', code: '📹' },
  { name: 'vhs', code: '📼' },
  { name: 'mag', code: '🔍' },
  { name: 'mag_right', code: '🔎' },
  { name: 'candle', code: '🕯️' },
  { name: 'bulb', code: '💡' },
  { name: 'flashlight', code: '🔦' },
  { name: 'izakaya_lantern', code: '🏮' },
  { name: 'diya_lamp', code: '🪔' },
  { name: 'notebook_with_decorative_cover', code: '📔' },
  { name: 'closed_book', code: '📕' },
  { name: 'book', code: '📖' },
  { name: 'green_book', code: '📗' },
  { name: 'blue_book', code: '📘' },
  { name: 'orange_book', code: '📙' },
  { name: 'books', code: '📚' },
  { name: 'notebook', code: '📓' },
  { name: 'ledger', code: '📒' },
  { name: 'page_with_curl', code: '📃' },
  { name: 'scroll', code: '📜' },
  { name: 'page_facing_up', code: '📄' },
  { name: 'newspaper', code: '📰' },
  { name: 'newspaper_roll', code: '🗞️' },
  { name: 'bookmark_tabs', code: '📑' },
  { name: 'bookmark', code: '🔖' },
  { name: 'label', code: '🏷️' },
  { name: 'moneybag', code: '💰' },
  { name: 'coin', code: '🪙' },
  { name: 'yen', code: '💴' },
  { name: 'dollar', code: '💵' },
  { name: 'euro', code: '💶' },
  { name: 'pound', code: '💷' },
  { name: 'money_with_wings', code: '💸' },
  { name: 'credit_card', code: '💳' },
  { name: 'receipt', code: '🧾' },
  { name: 'chart', code: '💹' },
  { name: 'envelope', code: '✉️' },
  { name: 'email', code: '📧' },
  { name: 'incoming_envelope', code: '📨' },
  { name: 'envelope_with_arrow', code: '📩' },
  { name: 'outbox_tray', code: '📤' },
  { name: 'inbox_tray', code: '📥' },
  { name: 'package', code: '📦' },
  { name: 'mailbox', code: '📫' },
  { name: 'mailbox_closed', code: '📪' },
  { name: 'mailbox_with_mail', code: '📬' },
  { name: 'mailbox_with_no_mail', code: '📭' },
  { name: 'postbox', code: '📮' },
  { name: 'ballot_box_with_ballot', code: '🗳️' },
  { name: 'pencil2', code: '✏️' },
  { name: 'black_nib', code: '✒️' },
  { name: 'fountain_pen', code: '🖊️' },
  { name: 'pen', code: '🖋️' },
  { name: 'paintbrush', code: '🖌️' },
  { name: 'crayon', code: '🖍️' },
  { name: 'memo', code: '📝' },
  { name: 'briefcase', code: '💼' },
  { name: 'file_folder', code: '📁' },
  { name: 'open_file_folder', code: '📂' },
  { name: 'card_index_dividers', code: '🗂️' },
  { name: 'calendar', code: '📅' },
  { name: 'date', code: '📆' },
  { name: 'spiral_notepad', code: '🗒️' },
  { name: 'spiral_calendar', code: '🗓️' },
  { name: 'card_index', code: '📇' },
  { name: 'chart_with_upwards_trend', code: '📈' },
  { name: 'chart_with_downwards_trend', code: '📉' },
  { name: 'bar_chart', code: '📊' },
  { name: 'clipboard', code: '📋' },
  { name: 'pushpin', code: '📌' },
  { name: 'round_pushpin', code: '📍' },
  { name: 'paperclip', code: '📎' },
  { name: 'paperclips', code: '🖇️' },
  { name: 'straight_ruler', code: '📏' },
  { name: 'triangular_ruler', code: '📐' },
  { name: 'scissors', code: '✂️' },
  { name: 'card_file_box', code: '🗃️' },
  { name: 'file_cabinet', code: '🗄️' },
  { name: 'wastebasket', code: '🗑️' },
  { name: 'lock', code: '🔒' },
  { name: 'unlock', code: '🔓' },
  { name: 'lock_with_ink_pen', code: '🔏' },
  { name: 'closed_lock_with_key', code: '🔐' },
  { name: 'key', code: '🔑' },
  { name: 'old_key', code: '🗝️' },
  { name: 'hammer', code: '🔨' },
  { name: 'axe', code: '🪓' },
  { name: 'pick', code: '⛏️' },
  { name: 'hammer_and_pick', code: '⚒️' },
  { name: 'hammer_and_wrench', code: '🛠️' },
  { name: 'dagger', code: '🗡️' },
  { name: 'crossed_swords', code: '⚔️' },
  { name: 'gun', code: '🔫' },
  { name: 'boomerang', code: '🪃' },
  { name: 'bow_and_arrow', code: '🏹' },
  { name: 'shield', code: '🛡️' },
  { name: 'carpentry_saw', code: '🪚' },
  { name: 'wrench', code: '🔧' },
  { name: 'screwdriver', code: '🪛' },
  { name: 'nut_and_bolt', code: '🔩' },
  { name: 'gear', code: '⚙️' },
  { name: 'probing_cane', code: '🦯' },
  { name: 'link', code: '🔗' },
  { name: 'chains', code: '⛓️' },
  { name: 'hook', code: '🪝' },
  { name: 'toolbox', code: '🧰' },
  { name: 'magnet', code: '🧲' },
  { name: 'ladder', code: '🪜' },
  { name: 'alchemy', code: '⚗️' },
  { name: 'test_tube', code: '🧪' },
  { name: 'petri_dish', code: '🧫' },
  { name: 'dna', code: '🧬' },
  { name: 'microscope', code: '🔬' },
  { name: 'telescope', code: '🔭' },
  { name: 'satellite', code: '📡' },
  { name: 'syringe', code: '💉' },
  { name: 'drop_of_blood', code: '🩸' },
  { name: 'pill', code: '💊' },
  { name: 'adhesive_bandage', code: '🩹' },
  { name: 'crutch', code: '🩼' },
  { name: 'stethoscope', code: '🩺' },
  { name: 'x-ray', code: '🩻' },
  { name: 'door', code: '🚪' },
  { name: 'elevator', code: '🛗' },
  { name: 'mirror', code: '🪞' },
  { name: 'window', code: '🪟' },
  { name: 'bed', code: '🛏️' },
  { name: 'couch_and_lamp', code: '🛋️' },
  { name: 'chair', code: '🪑' },
  { name: 'toilet', code: '🚽' },
  { name: 'plunger', code: '🪠' },
  { name: 'shower', code: '🚿' },
  { name: 'bathtub', code: '🛁' },
  { name: 'razor', code: '🪒' },
  { name: 'lotion_bottle', code: '🧴' },
  { name: 'safety_pin', code: '🧷' },
  { name: 'broom', code: '🧹' },
  { name: 'basket', code: '🧺' },
  { name: 'roll_of_paper', code: '🧻' },
  { name: 'bucket', code: '🪣' },
  { name: 'soap', code: '🧼' },
  { name: 'bubbles', code: '🫧' },
  { name: 'toothbrush', code: '🪥' },
  { name: 'sponge', code: '🧽' },
  { name: 'squeeze_bottle', code: '🧴' },
  { name: 'shopping_trolley', code: '🛒' },
  { name: 'smoking', code: '🚬' },
  { name: 'coffin', code: '⚰️' },
  { name: 'headstone', code: '🪦' },
  { name: 'funeral_urn', code: '⚱️' },
  { name: 'moyai', code: '🗿' },

  // ──────────────────────────────────────────
  // SYMBOLS
  // ──────────────────────────────────────────
  { header: true, icon: '☮️', code: 'symbols', label: 'Symbols' },
  { name: 'atm', code: '🏧' },
  { name: 'put_litter_in_its_place', code: '🚮' },
  { name: 'potable_water', code: '🚰' },
  { name: 'wheelchair', code: '♿' },
  { name: 'mens', code: '🚹' },
  { name: 'womens', code: '🚺' },
  { name: 'restroom', code: '🚻' },
  { name: 'baby_symbol', code: '🚼' },
  { name: 'wc', code: '🚾' },
  { name: 'passport_control', code: '🛂' },
  { name: 'customs', code: '🛃' },
  { name: 'baggage_claim', code: '🛄' },
  { name: 'left_luggage', code: '🛅' },
  { name: 'warning', code: '⚠️' },
  { name: 'children_crossing', code: '🚸' },
  { name: 'no_entry', code: '⛔' },
  { name: 'no_entry_sign', code: '🚫' },
  { name: 'no_bicycles', code: '🚳' },
  { name: 'no_smoking', code: '🚭' },
  { name: 'do_not_litter', code: '🚯' },
  { name: 'non-potable_water', code: '🚱' },
  { name: 'no_pedestrians', code: '🚷' },
  { name: 'no_mobile_phones', code: '📵' },
  { name: 'underage', code: '🔞' },
  { name: 'radioactive', code: '☢️' },
  { name: 'biohazard', code: '☣️' },
  { name: 'arrow_up', code: '⬆️' },
  { name: 'arrow_upper_right', code: '↗️' },
  { name: 'arrow_right', code: '➡️' },
  { name: 'arrow_lower_right', code: '↘️' },
  { name: 'arrow_down', code: '⬇️' },
  { name: 'arrow_lower_left', code: '↙️' },
  { name: 'arrow_left', code: '⬅️' },
  { name: 'arrow_upper_left', code: '↖️' },
  { name: 'arrow_up_down', code: '↕️' },
  { name: 'left_right_arrow', code: '↔️' },
  { name: 'arrows_counterclockwise', code: '🔄' },
  { name: 'arrow_right_hook', code: '↪️' },
  { name: 'leftwards_arrow_with_hook', code: '↩️' },
  { name: 'arrow_heading_up', code: '⤴️' },
  { name: 'arrow_heading_down', code: '⤵️' },
  { name: 'recycle', code: '♻️' },
  { name: 'sos', code: '🆘' },
  { name: 'end', code: '🔚' },
  { name: 'back', code: '🔙' },
  { name: 'on', code: '🔛' },
  { name: 'top', code: '🔝' },
  { name: 'soon', code: '🔜' },
  { name: 'place_of_worship', code: '🛐' },
  { name: 'star_and_crescent', code: '☪️' },
  { name: 'peace_symbol', code: '☮️' },
  { name: 'cross', code: '✝️' },
  { name: 'star_of_david', code: '✡️' },
  { name: 'white_check_mark', code: '✅' },
  { name: 'ballot_box_with_check', code: '☑️' },
  { name: 'heavy_check_mark', code: '✔️' },
  { name: 'x', code: '❌' },
  { name: 'negative_squared_cross_mark', code: '❎' },
  { name: 'heavy_plus_sign', code: '➕' },
  { name: 'heavy_minus_sign', code: '➖' },
  { name: 'heavy_division_sign', code: '➗' },
  { name: 'curly_loop', code: '➰' },
  { name: 'loop', code: '➿' },
  { name: 'question', code: '❓' },
  { name: 'grey_question', code: '❔' },
  { name: 'grey_exclamation', code: '❕' },
  { name: 'exclamation', code: '❗' },
  { name: 'wavy_dash', code: '〰️' },
  { name: 'copyright', code: '©️' },
  { name: 'registered', code: '®️' },
  { name: 'tm', code: '™️' },
  { name: 'hash', code: '#️⃣' },
  { name: 'asterisk', code: '*️⃣' },
  { name: 'zero', code: '0️⃣' },
  { name: 'one', code: '1️⃣' },
  { name: 'two', code: '2️⃣' },
  { name: 'three', code: '3️⃣' },
  { name: 'four', code: '4️⃣' },
  { name: 'five', code: '5️⃣' },
  { name: 'six', code: '6️⃣' },
  { name: 'seven', code: '7️⃣' },
  { name: 'eight', code: '8️⃣' },
  { name: 'nine', code: '9️⃣' },
  { name: 'keycap_ten', code: '🔟' },
  { name: 'capital_abcd', code: '🔠' },
  { name: 'abcd', code: '🔡' },
  { name: '1234', code: '🔢' },
  { name: 'symbols', code: '🔣' },
  { name: 'abc', code: '🔤' },
  { name: 'a', code: '🅰️' },
  { name: 'ab', code: '🆎' },
  { name: 'b', code: '🅱️' },
  { name: 'cl', code: '🆑' },
  { name: 'cool', code: '🆒' },
  { name: 'free', code: '🆓' },
  { name: 'information_source', code: 'ℹ️' },
  { name: 'id', code: '🆔' },
  { name: 'm', code: 'Ⓜ️' },
  { name: 'new', code: '🆕' },
  { name: 'ng', code: '🆖' },
  { name: 'o2', code: '🅾️' },
  { name: 'ok', code: '🆗' },
  { name: 'parking', code: '🅿️' },
  { name: 'sos', code: '🆘' },
  { name: 'up', code: '🆙' },
  { name: 'vs', code: '🆚' },
  { name: 'koko', code: '🈁' },
  { name: 'u7121', code: '🈚' },
  { name: 'u6307', code: '🈯' },
  { name: 'cinema', code: '🎦' },
  { name: 'signal_strength', code: '📶' },
  { name: 'koko2', code: '📳' },
  { name: 'vibration_mode', code: '📳' },
  { name: 'mobile_phone_off', code: '📴' },
  { name: 'female_sign', code: '♀️' },
  { name: 'male_sign', code: '♂️' },
  { name: 'infinity', code: '♾️' },
  { name: 'fleur_de_lis', code: '⚜️' },
  { name: 'beginner', code: '🔰' },
  { name: 'trident', code: '🔱' },
  { name: 'white_square_button', code: '🔳' },
  { name: 'black_square_button', code: '🔲' },
  { name: 'red_circle', code: '🔴' },
  { name: 'orange_circle', code: '🟠' },
  { name: 'yellow_circle', code: '🟡' },
  { name: 'green_circle', code: '🟢' },
  { name: 'blue_circle', code: '🔵' },
  { name: 'purple_circle', code: '🟣' },
  { name: 'brown_circle', code: '🟤' },
  { name: 'black_circle', code: '⚫' },
  { name: 'white_circle', code: '⚪' },
  { name: 'red_square', code: '🟥' },
  { name: 'orange_square', code: '🟧' },
  { name: 'yellow_square', code: '🟨' },
  { name: 'green_square', code: '🟩' },
  { name: 'blue_square', code: '🟦' },
  { name: 'purple_square', code: '🟪' },
  { name: 'brown_square', code: '🟫' },
  { name: 'black_large_square', code: '⬛' },
  { name: 'white_large_square', code: '⬜' },
  { name: 'small_red_triangle', code: '🔺' },
  { name: 'small_red_triangle_down', code: '🔻' },
  { name: 'diamond_shape_with_a_dot_inside', code: '💠' },
  { name: 'radio_button', code: '🔘' },
  { name: 'white_medium_square', code: '◻️' },
  { name: 'black_medium_square', code: '◼️' },
  { name: 'white_medium_small_square', code: '◽' },
  { name: 'black_medium_small_square', code: '◾' },
  { name: 'white_small_square', code: '▫️' },
  { name: 'black_small_square', code: '▪️' },

  // ──────────────────────────────────────────
  // FLAGS
  // ──────────────────────────────────────────
  { header: true, icon: '🏳️', code: 'flags', label: 'Flags' },
  { name: 'chequered_flag', code: '🏁' },
  { name: 'triangular_flag_on_post', code: '🚩' },
  { name: 'crossed_flags', code: '🎌' },
  { name: 'black_flag', code: '🏴' },
  { name: 'white_flag', code: '🏳️' },
  { name: 'rainbow_flag', code: '🏳️‍🌈' },
  { name: 'transgender_flag', code: '🏳️‍⚧️' },
  { name: 'pirate_flag', code: '🏴‍☠️' },
  { name: 'flag_us', code: '🇺🇸' },
  { name: 'flag_gb', code: '🇬🇧' },
  { name: 'flag_vn', code: '🇻🇳' },
  { name: 'flag_cn', code: '🇨🇳' },
  { name: 'flag_jp', code: '🇯🇵' },
  { name: 'flag_kr', code: '🇰🇷' },
  { name: 'flag_fr', code: '🇫🇷' },
  { name: 'flag_de', code: '🇩🇪' },
  { name: 'flag_es', code: '🇪🇸' },
  { name: 'flag_it', code: '🇮🇹' },
  { name: 'flag_pt', code: '🇵🇹' },
  { name: 'flag_ru', code: '🇷🇺' },
  { name: 'flag_in', code: '🇮🇳' },
  { name: 'flag_au', code: '🇦🇺' },
  { name: 'flag_ca', code: '🇨🇦' },
  { name: 'flag_br', code: '🇧🇷' },
  { name: 'flag_mx', code: '🇲🇽' },
  { name: 'flag_id', code: '🇮🇩' },
  { name: 'flag_th', code: '🇹🇭' },
  { name: 'flag_ph', code: '🇵🇭' },
  { name: 'flag_sg', code: '🇸🇬' },
  { name: 'flag_my', code: '🇲🇾' },
  { name: 'flag_eu', code: '🇪🇺' },
  { name: 'flag_un', code: '🇺🇳' },
];

export default emojis;
